#!/bin/sh
source /home/setup_environment_target
file0=/home/$PRODUCT_NAME/config/setmacIG
file1=/home/$PRODUCT_NAME/config/setmacOG
cp $file0 ${file0}.save
cp $file1 ${file1}.save
echo "export macaddr_eth0=$1" >> $file0
echo '/sbin/ifconfig eth0 down' >> $file0
echo '/sbin/ifconfig eth0 hw ether $macaddr_eth0' >> $file0

echo "export macaddr_eth1=$2" >> $file1
echo '/sbin/ifconfig eth1 down' >> $file1
echo '/sbin/ifconfig eth1 hw ether $macaddr_eth1' >> $file1
