#!/bin/sh
source /home/setup_environment_target

# Set up the internal ethernet interface.
file1=/home/$PRODUCT_NAME/config/setmacOG

# If the file exists, copy it to backup and delete original
if [  -f "$file1" ]
then
    cp $file1 ${file1}.save
    rm $file1
fi


if [ 'on' = $sh_dualether ]
then
        echo "export macaddr=$1" >> $file1
        echo '/sbin/ifconfig eth1 down' >> $file1
        echo '/sbin/ifconfig eth1 hw ether $macaddr' >> $file1
else
        echo "export macaddr=$1" >> $file1
        echo '/sbin/ifconfig eth0 down' >> $file1
        echo '/sbin/ifconfig eth0 hw ether $macaddr' >> $file1
fi

chmod a+x $file1



