#!/bin/sh

# Set ethernet MAC address for this device. Autogen file
# populated by the application during ethernet configuration.
# There is also a local script in this directory (newmac)
# which can be executed from the command line to populate
# this file.

# Set up the internal ethernet interface.
export macaddr=00:80:40:FF:00:C0
/sbin/ifconfig eth1 down
/sbin/ifconfig eth1 hw ether $macaddr
