#!/bin/sh

# Set ethernet MAC address for this device. Autogen file
# populated by the application during ethernet configuration.
# There is also a local script in this directory (newmac)
# which can be executed from the command line to populate
# this file.

export macaddr_eth1=00:80:40:FF:00:37
/sbin/ifconfig eth1 down
/sbin/ifconfig eth1 hw ether $macaddr_eth1
