#!/bin/sh

# Set ethernet MAC address for this device. Autogen file
# populated by the application during ethernet configuration.
# There is also a local script in this directory (newmac)
# which can be executed from the command line to populate
# this file.

export macaddr_eth0=FC:C2:3D:10:3B:6E
/sbin/ifconfig eth0 down
/sbin/ifconfig eth0 hw ether $macaddr_eth0
