#!/bin/bash
#

source ./setup_environment

export PUBLISH_COMMON_DIR=../common/

echo "Getting images from the deploy archive."
${PUBLISH_COMMON_DIR}getImages
echo "done!"

#echo "Customizing the target directory."
#./targetify
#echo "done!"

echo "Building the rootfs image."
if [ ! -d "./rootfs" ]; then
    mkdir ./rootfs
fi
if [ ! -d "./targetAux" ]; then
    mkdir ./targetAux
fi
echo "Building the ubifs image."
#sudo ./mkubifs
cp -p $PROJECT_IMAGES/fluke-full-image-${PROJECT_MACHINE}.ubi ./rootfs/ubi.img


echo "Setting image permissions."
sudo chmod 666 ./rootfs/ubi.img
sudo chgrp pmengr ./rootfs/ubi.img
sudo chgrp pmengr ./kernel/zImage
echo "done!"

echo "Building composite flash images."
/usr/bin/srec_cat \
./loader/u-boot-with-spl.sfp -Binary \
./DeviceTree/zImage-${PROJECT_NAME}_soc.dtb -Binary -Offset 0x00110000 \
./kernel/zImage -Binary -Offset 0x00200000 \
./fpga/${PROJECT_NAME}_OG.rbf -Binary -Offset 0x0800000 \
-Output ./rootfs/U10.flash -Motorola --address-length=4 -Data_Only

# Create binary image from Motorola S-Record.  Fill blank spaces
# with 0xff instead of 0x00.
/usr/bin/srec_cat ./rootfs/U10.flash -Motorola \
-Fill 0xff -over ./rootfs/U10.flash \
-Output ./rootfs/U10.bin -Binary
echo "U10 done!"
/usr/bin/srec_cat \
./rootfs/ubi.img -Binary \
-Output ./rootfs/U11.flash -Motorola --address-length=4 -Data_Only
/usr/bin/srec_cat ./rootfs/U11.flash -Motorola \
-Fill 0xff -over ./rootfs/U11.flash \
-Output ./rootfs/U11.bin -Binary
echo "U11 done!"
chgrp pmengr ./rootfs/U10.bin
chgrp pmengr ./rootfs/U11.bin
echo "Composite images created!"

BUILD_DATE=$(date +"%y_%m_%d")
RELEASE_FOLDER=${BUILD_DATE}_${PROJECT_NAME}
echo "Building release folder "$RELEASE_FOLDER

install -d ./release/$RELEASE_FOLDER/toolchain
install -d ./release/$RELEASE_FOLDER/zImage
install -d ./release/$RELEASE_FOLDER/rootfs
install -d ./release/$RELEASE_FOLDER/fpga
install -d ./release/$RELEASE_FOLDER/U10
install -d ./release/$RELEASE_FOLDER/U11
install -d ./release/$RELEASE_FOLDER/loader
#install -d ./release/$RELEASE_FOLDER/devicetree

cp -Rp ./toolchain/* ./release/${RELEASE_FOLDER}/toolchain/ 
cp -Rp ./DeviceTree ./release/${RELEASE_FOLDER}/.
cp -Rp ./loader ./release/${RELEASE_FOLDER}/.
cp -p ./kernel/zImage ./release/${RELEASE_FOLDER}/zImage/. 
cp -p ./rootfs/ubi.img ./release/${RELEASE_FOLDER}/rootfs/. 
cp -p ./rootfs/U10.bin ./release/${RELEASE_FOLDER}/U10/. 
cp -p ./rootfs/U11.bin ./release/${RELEASE_FOLDER}/U11/. 
cp -p ./fpga/* ./release/${RELEASE_FOLDER}/fpga/.

