#!/bin/sh

# Get the ethernet TCP/IP settings unique to this instrument.
source /home/setup_environment_target

# Set the MAC addresses on the external outguard interface.
/home/Caldera/config/setmacOG

# Set up the internal ethernet interface.
if [ 'on' = $sh_dualether ]
then
    sh_extether=eth1
else
    sh_extether=eth0
fi

# Set up the external ethernet interface.
touch /etc/hosts
hostname $sh_hostname
if [ 'on' = $sh_dhcp ]
then
    /sbin/udhcpc -i $sh_extether -t 0 -x hostname:$sh_hostname -q &
else
    /sbin/ifconfig $sh_extether $sh_ipaddr netmask $sh_netmask
    /sbin/route add default gw $sh_gateway
fi
