#!/bin/sh
source /home/setup_environment_target

if [ ! -d "/config" ]; then
    mkdir /config
fi
mount -t configfs configfs /config
mkdir /config/device-tree/overlays/$PRODUCT_NAME
#echo zImage-Caldera_soc_overlay.dtb > /config/device-tree/overlays/$PRODUCT_NAME/path
cat /boot/Caldera_soc_overlay.dtb > /config/device-tree/overlays/$PRODUCT_NAME/dtbo
